// Auto-generated by Tools/gen_version.sh — DO NOT EDIT.
import Foundation

public enum ExamManagerVersion {
    public static let majorIndex: Int = 1
    public static let minorLetter: String = "A"
    public static let build: Int = 23
    public static let channel: String = "d"

    public static let marketingVersion: String = "2.0"
    public static let label: String = "1A23d"
}
