#!/bin/bash
set -euo pipefail

VERSION_DIR="${1:?version dir missing}"
OUT_SWIFT="${2:?output swift path missing}"

MAJOR_INDEX_FILE="${VERSION_DIR}/major_index"
MINOR_LETTER_FILE="${VERSION_DIR}/minor_letter"
CHANNEL_FILE="${VERSION_DIR}/channel"
BUILD_FILE="${VERSION_DIR}/build_number"
LABEL_FILE="${VERSION_DIR}/build_label"

[[ -f "$MAJOR_INDEX_FILE" ]] || echo "1" > "$MAJOR_INDEX_FILE"
[[ -f "$MINOR_LETTER_FILE" ]] || echo "A" > "$MINOR_LETTER_FILE"
[[ -f "$CHANNEL_FILE" ]] || echo "n" > "$CHANNEL_FILE"
[[ -f "$BUILD_FILE" ]] || echo "0" > "$BUILD_FILE"

MAJOR_INDEX="$(tr -d '[:space:]' < "$MAJOR_INDEX_FILE")"
MINOR_LETTER="$(tr -d '[:space:]' < "$MINOR_LETTER_FILE")"
CHANNEL="$(tr -d '[:space:]' < "$CHANNEL_FILE")"
BUILD="$(tr -d '[:space:]' < "$BUILD_FILE")"

BUILD=$((BUILD + 1))
echo "$BUILD" > "$BUILD_FILE"

ord() { LC_CTYPE=C printf '%d' "'$1"; }
A_ORD=$(ord "A")
L_ORD=$(ord "$MINOR_LETTER")
MINOR_NUM=$((L_ORD - A_ORD))
if [[ $MINOR_NUM -lt 0 ]]; then MINOR_NUM=0; fi

MARKETING_MAJOR=$((MAJOR_INDEX + 1))
MARKETING_VERSION="${MARKETING_MAJOR}.${MINOR_NUM}"
LABEL="${MAJOR_INDEX}${MINOR_LETTER}${BUILD}${CHANNEL}"
echo "$LABEL" > "$LABEL_FILE"

cat > "$OUT_SWIFT" <<EOF
// Auto-generated by Tools/gen_version.sh — DO NOT EDIT.
import Foundation

public enum ExamManagerVersion {
    public static let majorIndex: Int = ${MAJOR_INDEX}
    public static let minorLetter: String = "${MINOR_LETTER}"
    public static let build: Int = ${BUILD}
    public static let channel: String = "${CHANNEL}"

    public static let marketingVersion: String = "${MARKETING_VERSION}"
    public static let label: String = "${LABEL}"
}
EOF

cat > "${VERSION_DIR}/version.mk" <<EOF
# Auto-generated — DO NOT EDIT.
VERSION := ${MARKETING_VERSION}
EOF

echo "Generated version: ${LABEL} (pkg VERSION=${MARKETING_VERSION})"
